#===-------------------- Makefile -- to build iHRC    -------------------===//
#
# Copyright (c) 2013 Intel Corporation. All rights reserved.
#                     The iHRC Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE-iHRC.TXT for details.
#
#===----------------------------------------------------------------------===
LEVEL = ../../..
LIBRARYNAME = LLVMiHRC
BUILD_ARCHIVE = 1
#LOADABLE_MODULE = 1
#USEDLIBS =

# If we don't need RTTI or EH, there's no reason to export anything
# from the iHRC plugin.
# ifneq ($(REQUIRES_RTTI), 1)
# ifneq ($(REQUIRES_EH), 1)
# EXPORTED_SYMBOL_FILE = $(PROJ_SRC_DIR)/iHRC.exports
# endif
# endif

include $(LEVEL)/Makefile.common

